# Generated by Django 5.0.6 on 2024-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer_details',
            name='Dealer_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
